In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("IMDB-Movie-Dataset(2023-1951).csv")
movies.head(1)

Unnamed: 0    movie_id movie_name  year             genre  \
0           0  tt15354916      Jawan  2023  Action, Thriller   

                                            overview director  \
0  A high-octane action thriller which outlines t...    Atlee   

                                                cast  
0  Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...

In [3]:
#lets summorise our selected data
#genres
#id
#keywords
#title
#overview
#cast
#crew
pross_movie = movies[['movie_id','movie_name','overview', 'genre','director',]]

In [4]:
#checking for null data
pross_movie.isnull().sum()


movie_id      0
movie_name    0
overview      0
genre         0
director      0
dtype: int64

In [5]:
pross_movie['overview'] = pross_movie['overview'].apply(lambda x: x.split())
pross_movie['director'] = pross_movie['director'].apply(lambda x: x.split())
pross_movie['genre'] = pross_movie['genre'].apply(lambda x: x.split())


C:\Users\badal\AppData\Local\Temp\ipykernel_6140\2345226579.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pross_movie['overview'] = pross_movie['overview'].apply(lambda x: x.split())
C:\Users\badal\AppData\Local\Temp\ipykernel_6140\2345226579.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pross_movie['director'] = pross_movie['director'].apply(lambda x: x.split())
C:\Users\badal\AppData\Local\Temp\ipykernel_6140\2345226579.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a 

In [6]:
pross_movie['genre'] = pross_movie["genre"].apply(lambda x:[i.replace(" ","") for i in x])
pross_movie['director'] = pross_movie["director"].apply(lambda x:[i.replace(" ","") for i in x])
pross_movie['overview'] = pross_movie["overview"].apply(lambda x:[i.replace(" ","") for i in x])


C:\Users\badal\AppData\Local\Temp\ipykernel_6140\1544121313.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pross_movie['genre'] = pross_movie["genre"].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\badal\AppData\Local\Temp\ipykernel_6140\1544121313.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pross_movie['director'] = pross_movie["director"].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\badal\AppData\Local\Temp\ipykernel_6140\1544121313.py:3: SettingWithCopyWarning: 
A value i

In [7]:
pross_movie['tags'] = pross_movie['overview'] + pross_movie["genre"]+ pross_movie["director"]

C:\Users\badal\AppData\Local\Temp\ipykernel_6140\841667751.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pross_movie['tags'] = pross_movie['overview'] + pross_movie["genre"]+ pross_movie["director"]


In [8]:
data_set = pross_movie[['movie_id',"movie_name","tags"]]

In [9]:
data_set.head()

movie_id                       movie_name  \
0  tt15354916                            Jawan   
1  tt15748830                       Jaane Jaan   
2  tt11663228                           Jailer   
3  tt14993250  Rocky Aur Rani Kii Prem Kahaani   
4  tt15732324                            OMG 2   

                                                tags  
0  [A, high-octane, action, thriller, which, outl...  
1  [A, single, mother, and, her, daughter, who, c...  
2  [A, retired, jailer, goes, on, a, manhunt, to,...  
3  [Flamboyant, Punjabi, Rocky, and, intellectual...  
4  [An, unhappy, civilian, asks, the, court, to, ...

In [10]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


In [11]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return  " ".join(y)

In [12]:
data_set['tags'] = data_set['tags'].apply(lambda x:" ".join(x))
data_set['tags'][0]

C:\Users\badal\AppData\Local\Temp\ipykernel_6140\2735174518.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_set['tags'] = data_set['tags'].apply(lambda x:" ".join(x))


'A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society. Action, Thriller Atlee'

In [13]:
data_set['tags'] = data_set['tags'].apply(lambda x:x.lower())

C:\Users\badal\AppData\Local\Temp\ipykernel_6140\3665845938.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_set['tags'] = data_set['tags'].apply(lambda x:x.lower())


In [14]:
data_set['tags']=data_set['tags'].apply(stem)

C:\Users\badal\AppData\Local\Temp\ipykernel_6140\2666284055.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_set['tags']=data_set['tags'].apply(stem)


In [15]:
data_set['tags'][0]

'a high-octan action thriller which outlin the emot journey of a man who is set to rectifi the wrong in the society. action, thriller atle'

In [16]:
data_set['tags'][1]

'a singl mother and her daughter who commit a crime and a neighbor who help them cover it up amidst a polic investigation. crime, drama, mysteri sujoy ghosh'

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer(max_features = 5000,stop_words = 'english')
vectors = cv.fit_transform(data_set['tags']).toarray()
# converted the data set in the form of vectors
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
features_name = cv.get_feature_names_out()

In [20]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zoya', 'zubair', 'zubeidaa'],
      dtype=object)

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.11470787, ..., 0.        , 0.        ,
        0.08333333],
       [0.        , 1.        , 0.10814761, ..., 0.        , 0.08466675,
        0.03928371],
       [0.11470787, 0.10814761, 1.        , ..., 0.05564149, 0.12361285,
        0.22941573],
       ...,
       [0.        , 0.        , 0.05564149, ..., 1.        , 0.08712137,
        0.12126781],
       [0.        , 0.08466675, 0.12361285, ..., 0.08712137, 1.        ,
        0.23947374],
       [0.08333333, 0.03928371, 0.22941573, ..., 0.12126781, 0.23947374,
        1.        ]])

In [23]:
similarity = cosine_similarity(vectors)

In [24]:
similarity[2]

array([0.11470787, 0.10814761, 1.        , ..., 0.05564149, 0.12361285,
       0.22941573])

In [25]:
def recommend(movie):
    movie_index = data_set[data_set['movie_name'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(data_set.iloc[i[0]].movie_name)

In [27]:
recommend("Jawan")

Anek
Ruslaan
Thugs
Martin
Aadhi Bhagavan


In [28]:
data_set.to_dict()

{'movie_id': {0: 'tt15354916',
  1: 'tt15748830',
  2: 'tt11663228',
  3: 'tt14993250',
  4: 'tt15732324',
  5: 'tt18266472',
  6: 'tt18561736',
  7: 'tt3691740',
  8: 'tt12844910',
  9: 'tt15464390',
  10: 'tt1187043',
  11: 'tt14914988',
  12: 'tt3741834',
  13: 'tt13131610',
  14: 'tt22188452',
  15: 'tt28568397',
  16: 'tt21908676',
  17: 'tt15441054',
  18: 'tt27542289',
  19: 'tt0454876',
  20: 'tt0249371',
  21: 'tt0838221',
  22: 'tt5074352',
  23: 'tt8239946',
  24: 'tt15428134',
  25: 'tt24485052',
  26: 'tt1954470',
  27: 'tt15433600',
  28: 'tt13751694',
  29: 'tt15891388',
  30: 'tt19755170',
  31: 'tt6277462',
  32: 'tt20913276',
  33: 'tt18411490',
  34: 'tt8672856',
  35: 'tt15501640',
  36: 'tt0083987',
  37: 'tt2338151',
  38: 'tt1188996',
  39: 'tt3405236',
  40: 'tt26324936',
  41: 'tt8108198',
  42: 'tt23036080',
  43: 'tt22086334',
  44: 'tt15380630',
  45: 'tt0986264',
  46: 'tt4430212',
  47: 'tt22297828',
  48: 'tt10083340',
  49: 'tt27012110',
  50: 'tt1524524

In [29]:
import pickle
pickle.dump(data_set.to_dict(),open('movie_hindi.pkl','wb'))

In [30]:
pickle.dump(similarity,open('similarity_hindi.pkl','wb'))